pipeline {
    agent any
    stages {
        stage('Clone repository') {
            steps {
                git 'https://github.com/username/my-node-app.git'
            }
        }

        stage('Build') {
            steps {
                script {
                    dockerImage = docker.build("username/my-node-app:latest")
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    docker.image("username/my-node-app:latest").inside {
                        // הפקודה שמריצה את קובץ הבדיקות יחידה
                        sh 'python -m unittest tests/test_calc.py'
                    }
                }
            }
        }

        stage('Push Docker image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
                        dockerImage.push()
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    docker.image("username/my-node-app:latest").inside {
                        sh 'npm start'
                    }
                }
            }
        }
    }
}
